global:
  discordSecret: OTg3MzYxNjQ4MDQ4MjI2MzQ2.G-ozdM.8utQQ2nimYtqtP2ZLWAG6HwjdNfwBzNrT0nGno

  database:
    connectionString: mongodb+srv://avatar:hailMing@scratch.jmxvp.mongodb.net
    databaseName: hal

  logging:
    logMessages: false

  options:
    parseBotMessages: false

guilds:

  - name: "Arkane Systems"

  - name: "The Associated Worlds"
